apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    environment: classroom
    application: web-server
status:
  loadBalancer: {}